import type { Metadata } from "next";
import "@/app/globals.css";
import Navbar from '@/components/navbar';
import { Inter } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Windoor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
       <body className={inter.variable}><Navbar></Navbar>{children}</body>
    </html>
  );
}